### ISSUE TITLE
Failed to load API definition - Error

### ISSUE THREAD

**Issue by Kum4r4n** [Burgyn/MMLib.SwaggerForOcelot#23]
hi,  
recently I install your Package but it dose not work for me,

its say 
![image](https://user-images.githubusercontent.com/31638942/57438832-6944f880-7262-11e9-93e3-a7d34b6982d6.png)

How can i fix that!

i am working with Microservice

**Comment by Burgyn** [comment]
Hi,
thanks for your report.

Please can you provide your `ocelot.json` configuration?

Thanks.

**Comment by Kum4r4n** [comment]
this is my 
```
{
  "ReRoutes": [
    {
      "DownstreamPathTemplate": "/{everything}",
      "DownstreamScheme": "http",
      "DownstreamHostAndPorts": [
        {
          "Host": "industryapi",
          "Port": 80
        }
      ],
      "UpstreamPathTemplate": "/api/I/{everything}",
      "UpstreamHttpMethod": [ "POST", "PUT", "GET" ],
      

    },
    {
      "DownstreamPathTemplate": "/{everything}",
      "DownstreamScheme": "http",
      "DownstreamHostAndPorts": [
        {
          "Host": "logisticapi",
          "Port": 80
        }
      ],
      "UpstreamPathTemplate": "/api/L/{everything}",
      "UpstreamHttpMethod": [ "POST", "PUT", "GET" ],
      "SwaggerKey": "Logistic"
    },
    {
      "DownstreamPathTemplate": "/api/OrderAPI/{everything}",
      "DownstreamScheme": "http",
      "DownstreamHostAndPorts": [
        {
          "Host": "orderapi",
          "Port": 80
        }
      ],
      "UpstreamPathTemplate": "/api/O/{everything}",
      "UpstreamHttpMethod": [ "POST", "PUT", "GET" ]
    }
    //,

    //{
    //  "DownstreamPathTemplate": "/swagger/index.html",
    //  "DownstreamScheme": "http",
    //  "DownstreamHostAndPorts": [
    //    {
    //      "Host": "industryapi",
    //      "Port": 80
    //    }
    //  ],
    //  "UpstreamPathTemplate": "/api/IndustryAPI/swagger",
    //  "UpstreamHttpMethod": [ "POST", "PUT", "GET" ]
    //}

  ],

  "SwaggerEndPoints": [
    {
      "Key": "Industry",
      "Config": [
        {
          "Name": "Industry API",
          "Version": "v1",
          "Url": "http://localhost:51010/swagger/v1/swagger.json"

        }
      ]
    },

    {
      "Key": "Logistic",
      "Config": [
        {
          "Name": "Logistic API",
          "Version": "v1",
          "Url": "http://localhost:51020/swagger/v1/swagger.json"

        }
      ]
    }
  ],


  "GlobalConfiguration": {
    "RequestIdKey": "OcRequestId",
    "AdministrationPath": "/administration"
  }
}
```

**Comment by Burgyn** [comment]
Hi,
I apology, I cannot reproduce this behaviour.

- Are you sure that swagger docs for `Industry` is accessible from `http://localhost:51010/swagger/v1/swagger.json`?
- Added you `services.AddSwaggerForOcelot(Configuration);` in `ConfigureServices` method in `Startup` class?
- Added you `app.UseSwaggerForOcelotUI(Configuration);` in `Configure` method in `Startup` class?

**Comment by Kum4r4n** [comment]
I used all of the thing what you say, but still i can't fix that   
please help me on it !

**Comment by Burgyn** [comment]
please, you can provide a sample where this behavior is isolated

**Comment by Kum4r4n** [comment]
this is our project

we are using microservice with docker 
and all of them separate projects with solution. normally swagger work with separately. 
we had api gate way for all service.  

i want to access all the service with one baseURL with api gate way in this case all of them are working good, the problem is swagger didn't work on api gate way i want to access all service swagger from api gate way.

**Comment by Burgyn** [comment]
I understand, this is main reason why this project was created. For microservices with one base api gateway base url. Where we want access to documentation for all downstream services in one place.

---

A typical problem when you get `500 Internal Server Error` is that ApiGateway doesn't have access to `SwaggerEndpoint.Url` in your case `http://localhost:51010/swagger/v1/swagger.json`.


Are you sure your ApiGateway has access to this address? Can't be the problem in Docker configurations?

Doesn't it work when you use the following configuration?

```
"SwaggerEndPoints": [
    {
      "Key": "Industry",
      "Config": [
        {
          "Name": "Industry API",
          "Version": "v1",
          "Url": "http://industryapi:80/swagger/v1/swagger.json"
        }
      ]
    },
    {
      "Key": "Logistic",
      "Config": [
        {
          "Name": "Logistic API",
          "Version": "v1",
          "Url": "http://logisticapi:80/swagger/v1/swagger.json"
        }
      ]
    }
  ]
```

By the way, in the ReRout configurations for the `industryapi` you are missing `SwaggerKey`, but this does not cause this error.

**Comment by Kum4r4n** [comment]
http://localhost:51010/swagger/v1/swagger.json this one is working fine,  

but its always shows same error.

this is my Docker Cofiguration file 

```
services:

  apigw:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "51000:80"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  industryapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionString=${ESHOP_AZURE_INDUSTRY_DB:-Server=sqlserver ; Database=IndustryDb; User Id=sa;Password=8jkGh47hnDw89Haq8LN2}
    ports:
      - "51010:80"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro


  logisticapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionString=${ESHOP_AZURE_INDUSTRY_DB:-Server=sqlserver ; Database=LogisticDb; User Id=sa;Password=8jkGh47hnDw89Haq8LN2}
    ports:
      - "51020:80"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

```



![image](https://user-images.githubusercontent.com/31638942/57506729-4c6bfc00-731a-11e9-9a3b-88bfe7c35506.png)
